### ISSUE TITLE
Remove Keybindings for Fold & Unfold

### ISSUE THREAD

**Issue by prog-rajkamal** [robaboyd/vs-org#82]
vs-org adds keybindings for Fold (TAB) and Unfold(SHIFT+TAB) for vsorg files

this is unnecessary, as vscode offers default keybindings for Fold(Ctrl+Shift+[ ) and unfold (Ctrl+Shift+]) for all file types.

**Comment by doncabreraphone** [comment]
Vote against this. I'm actually using the TAB feature. Its easier on some keyboards to just hit TAB instead.

**Comment by prog-rajkamal** [comment]
@doncabreraphone 
If you want, you can always add custom keybindings for your vscode installation.

However, by keeping it in default, it can't be removed.

As the pr is merged, I am closing this issue
